export const ARTICLE_GET_LATEST = 'ARTICLE_GET_LATEST';
export const ARTICLE_GET_SEARCH_RESULTS = 'ARTICLE_GET_SEARCH_RESULTS';
export const ARTICLE_GET_BY_ID = 'ARTICLE_GET_BY_ID';
export const ARTICLE_GET_RELATED_ARTICLES = 'ARTICLE_GET_RELATED_ARTICLES';

export const ARTICLE_CREATE = 'ARTICLE_CREATE';
export const ARTICLE_EDIT_BY_ID = 'ARTICLE_EDIT_BY_ID';
export const ARTICLE_UPDATE_BY_ID = 'ARTICLE_UPDATE_BY_ID';
export const ARTICLE_DELETE_BY_ID = 'ARTICLE_DELETE_BY_ID';

export const MEMBER_LOGIN = 'MEMBER_LOGIN';
export const MEMBER_LOGOUT = 'MEMBER_LOGOUT';
export const MEMBER_LOAD_AUTH = 'MEMBER_LOAD_AUTH';
export const MEMBER_GET_MY_ARTICLES = 'MEMBER_GET_MY_ARTICLES';

export const CONTACT_SAVE = 'CONTACT_SAVE';